name: Daily Commit

on:
  schedule:
    - cron: "20 9 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2000237@ds.study.iitm.ac.in
        uses: actions/checkout@v4
      - run: git config --global user.email "23f2000237@ds.study.iitm.ac.in"
