name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '12 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 23f2000237@ds.study.iitm.ac.in
      run: |
        echo "Running!"
